### ISSUE TITLE
Game crashes on launch after update.

### ISSUE THREAD

**Issue by eeach** [darkxex/UnCapFF4PRemaster#1]
Game loads to the title / menu screen.  When choosing 'load game' or 'new game', the title screen vanishes and the loading screen launches... but then vanishes. Shortly after, Steam shows the game is closed. 

I've reinstalled FF4PR. Ensured that it runs properly in an unmodded state. And then only installed UnCapFF4PRemaster to produce this issue. Setting the framerate back to 60 does not resolve the issue.

**Comment by darkxex** [comment]
Thanks for the news, I will update this tomorrow.

**Comment by joecatarata** [comment]
Having a similar issue as well. Maybe the new update on October 1 caused the issue?

**Comment by darkxex** [comment]
Así es, cada vez que el juego se actualiza, esta app dejará de funcionar hasta su actualización.

**Comment by joecatarata** [comment]
Ahh I see. Here's hoping that the tool gets updated. Really amazing work!

**Comment by darkxex** [comment]
https://github.com/darkxex/UnCapFF4PRemaster/releases/tag/1.1 updated to last build.
