### ISSUE TITLE
Frame rate stay at 60 even if i set it to higher values

### ISSUE THREAD

**Issue by Gianluca90** [darkxex/UnCapFF4PRemaster#2]
Hi,
i downloaded your exe and put it into the folder of FFIV Pixel Remaster. I tried to change value (like 120, or 140), but when i use Riva Tuner to check frame rate, it's stay at 60 fps no matter what. 
The game received a patch on august 2022, could it be the cause?
Thanks

**Comment by darkxex** [comment]
test with this.
https://github.com/darkxex/UnCapFF4PRemaster/releases/tag/1.2
